---
name: actionlint
on:
  push:
    branches: [main]
    paths:
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - .github/**
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.1.1-0
        with:
          aqua_version: v1.20.1
      - run: actionlint -ignore "duplicate value"
